"""empty message

Revision ID: dc2f30c2e573
Revises: e73dc87b7961
Create Date: 2023-06-30 15:30:09.340163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc2f30c2e573'
down_revision = 'e73dc87b7961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bid',
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['create_offers.offer_id'], ),
    sa.PrimaryKeyConstraint('bid_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bid')
    # ### end Alembic commands ###
